このページでは、バージョン管理システム「git」のインストールについて説明します。

Gitのインストール
======================

Gitの公式ページのダウンロードページヘ向かってください。
するとダウンロードへのリンクがありますので、それをクリックしてください。

`Git - Downloads`<https://git-scm.com/downloads>_

.. image:: img/build_environment/git_download.png

インストールが成功したと思ったら、「コマンドプロンプト」もしくは「ターミナル」を開いて、
以下のコマンドを入力してみてください。::

    git --version

インストールしたgitのバージョンが表示されれば成功です。

コマンド操作が嫌な人向け: Git-Colaのインストール
==================================================

Gitは基本的にコマンド操作です。以下のコマンドをわかっていれば問題なく使えます。

OS操作コマンド
------------------

+ cd
+ dir（ls)

Gitのコマンド
-------------------
+ git clone
+ git checkout -b
+ git add
+ git commit
+ git push
+ git pull

ただし、これらを使いこなせる気がしないという方は、「Git-Cola」のインストールをオススメします。

`Download git-cola`<https://git-cola.github.io/downloads.html>_

見た目は少々ダサいですが、コマンド操作を間違えて、書いたファイルが無くなるという事故
が無くなるよりは良いでしょう。
